cc_library(
    name = "wal_cc_proto",
    srcs = [
        "wal.pb.cc",
    ],
    hdrs = [
        "wal.pb.h",
    ],
    linkopts = [
        "-lprotobuf",
    ],
    visibility = ["//visibility:public"],
)
