cc_library(
    name = "raft_proto",
    srcs = [
        "raft.pb.cc",
    ],
    hdrs = [
        "raft.pb.h",
    ],
    linkopts = [
        "-lprotobuf",
    ],
    visibility = ["//visibility:public"],
)
